### ISSUE TITLE
Upgrade Apple Provider dependency for full PHP 8 support

### ISSUE THREAD

**Issue by nea** [Ahilmurugesan/socialite-apple-helper#10]
Ahoi

I just upgraded everything to fool around with PHP 8 and I jumped into a dependency clash to fully be able to upgrade.

The Helper requires `lcobucci/jwt` in version ^3.3, but PHP 8 support was only added to ^4.0 (https://github.com/lcobucci/jwt/releases/tag/4.0.0). 

Would you be able to apply that dependency allowance/requirement, too?

Thanks a lot in advance

**Comment by Adam2Marsh** [comment]
Hiya @nea 

I've just submitted a pull request which has the upgrade which should allow this package to work with php 8.  \

You can see it here - https://github.com/Ahilmurugesan/socialite-apple-helper/pull/11

**Comment by Ahilmurugesan** [comment]
Merged the pull request.
