### ISSUE TITLE
I not get proper user email and user name in apple token

### ISSUE THREAD

**Issue by haritartlabs** [Ahilmurugesan/socialite-apple-helper#2]
After installing this package in my laravel project. I got user details form apple token. but in this response, I got the user name became "null" and email id does not match with user email id (might be its encrypted email id). so please can help me with how to get a proper user email id and user name.

**Comment by vonec** [comment]
hi @haritartlabs, according to [documentation](https://socialiteproviders.netlify.app/providers/apple.html#_5-usage)

>Apple sends the user name only once during the initial authorization, subsequent authorization request only have email and provider user id. So it is advisable to save the user name during the initial request and associate it with the provider user id.

and with regards to email, if the end-user doesn't allow to share the email, Apple will provide a private relay email address (ends with @privaterelay.appleid.com) which is unique to every user - app combination, you can save it and send emails to the private-relay following [Apple documentation](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/communicating_using_the_private_email_relay_service) , if you still insist on getting the direct email address, you need to collect it post auth using a separate form. We will extend this functionality on this package asap.

if you need any further assistance do reply back, and please kindly close the ticket if you feel you got your solution :)

**Comment by haritartlabs** [comment]
Thanks for your reply, yeah I referred docs while getting a token from the client side if the user selects the hidden email we will get a unique email generated by apple, even though the user allows the same email we are getting and what about not getting username any idea?

**Comment by haritartlabs** [comment]
@vonec Thanks for your reply now I am clear with email and what about username how can I get the username of the user.

Thanks in advance!

**Comment by vonec** [comment]
You will receive user name only once ( the first time ) you authorize your apple account , for subsequent requests apple will not send the username ``$user->getName();``

**Comment by haritartlabs** [comment]
@vonec Thanks for your support
