### ISSUE TITLE
socialite-apple-helper installation issue in laravel 5.4

### ISSUE THREAD

**Issue by haritartlabs** [Ahilmurugesan/socialite-apple-helper#3]
@vonec, I try to install the socialite-apple-helper package in laravel 5.4. but it's showing error for while installation

Note: The latest version of laravel everything working fine. might be it's lower version issue so please suggestions something to fix the issue in laravel 5.4

**Comment by vonec** [comment]
we have not tested it beyond Laravel 6, but since you are asking we will definitely try to support Laravel 5.4, give us some time to look into this. thank you for notifying the issue.

**Comment by haritartlabs** [comment]
@vonec Thank you for your support. After, I am getting the "BadMethodCallException" error message after passing user apple access token to Socialite. If you have any idea please let me know for this error.

Please find the error message below mention it.


(1/1) BadMethodCallExceptionMethod filled does not exist.
--
in Macroable.php line 74
at Request->__call('filled', array('user'))in Provider.php line 199
at Provider->mapUserToObject(array('iss' => 'https://appleid.apple.com', 'aud' => 'com.archerreview.nclex.dev', 'exp' => 1594974618, 'iat' => 1594974018, 'sub' => '000030.4ee98b409a824497a6e65580634e8482.1032', 'c_hash' => 'J4PtT-9sSoXaSejRv4hXLw', 'email' => 'b4yr358dv5@privaterelay.appleid.com', 'email_verified' => 'true', 'is_private_email' => 'true', 'auth_time' => 1594974018, 'nonce_supported' => true))in AbstractProvider.php line 232
at AbstractProvider->userFromToken('eyJraWQiOiI4NkQ4OEtmIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmFyY2hlcnJldmlldy5uY2xleC5kZXYiLCJleHAiOjE1OTQ5NzQ2MTgsImlhdCI6MTU5NDk3NDAxOCwic3ViIjoiMDAwMDMwLjRlZTk4YjQwOWE4MjQ0OTdhNmU2NTU4MDYzNGU4NDgyLjEwMzIiLCJjX2hhc2giOiJKNFB0VC05c1NvWGFTZWpSdjRoWEx3IiwiZW1haWwiOiJiNHlyMzU4ZHY1QHByaXZhdGVyZWxheS5hcHBsZWlkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImlzX3ByaXZhdGVfZW1haWwiOiJ0cnVlIiwiYXV0aF90aW1lIjoxNTk0OTc0MDE4LCJub25jZV9zdXBwb3J0ZWQiOnRydWV9.PByCfI_urvdBQC4PNBV2Bmnn9-OGeKPY7s3d0TIePOJqjAipJPuhnb7w4Zy-rmNhEKhrbVARMtPm0zrJlwzhBXm336gnb-CPHNlV6KNUVsXXCv5uzRHswGXeuRKRZiDrNgrjAS4aE5UY7z074kaaBcKxsUoAah77cOjN2xsiGTDRhQI5CkiE5s9D3hCVMa0rH2NK3MPPRksj77v0QOiQazWtqW6bbtmAX4Ex_CoLu9sfPoNMd-wdLcD367LR1dXnaS_yC7K2ClbzGQpcYdgupPdjZxOh2QoeJBkYkZEgewey6_t3iOpj1YqcyeNK8MD0_kcb6bQW7mDux6FROcwVlw')in AuthController.php line 567
at AuthController->registerAppleUser(object(Request))
at call_user_func_array(array(object(AuthController), 'registerAppleUser'), array(object(Request)))in Controller.php line 55
at Controller->callAction('registerAppleUser', array(object(Request)))in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(AuthController), 'registerAppleUser')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ThrottleRequests.php line 49
at ThrottleRequests->handle(object(Request), object(Closure), '60', '1')in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Cors.php line 27
at Cors->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ExceptionHandlerMiddleware.php line 20
at ExceptionHandlerMiddleware->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in PrintRequestLog.php line 40
at PrintRequestLog->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in OAuthExceptionHandlerMiddleware.php line 36
at OAuthExceptionHandlerMiddleware->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 53
at require_once('/home/indglobal/Desktop/archer-review-web/public/index.php')in server.php line 21

**Comment by vonec** [comment]
we are aware of this issue we will be modifying this to clear this tomorrow. Most probably this should be working fine by Monday. Please hang on.

**Comment by Ahilmurugesan** [comment]
@haritartlabs [Pull Request](https://github.com/SocialiteProviders/Apple/pull/4) is in progress. Kindly wait for some more time, we will update here once the merge is complete.

**Comment by masticore252** [comment]
Hi @haritartlabs, fortunately for us, Laravel's `Illuminate\Http\Request` class uses `Illuminate\Support\Macroable` trait, so you can add new methods to the request object at runtime

I solved this in my project by taking a look at the implementation of "filled" in `Illuminate\Http\Concerns\InteractsWithInput` (this is in laravel >=5.5) and adding it to the request as a macro, you can see the code in the bug report I created [here](https://github.com/SocialiteProviders/Apple/issues/5)

That way it will work in Laravel 5.4 until the pull request is merged

**Comment by Ahilmurugesan** [comment]
@haritartlabs [Pull Request](https://github.com/SocialiteProviders/Providers/pull/479) has been merged. It is fixed.
