### ISSUE TITLE
Bug report: condition is always true.

### ISSUE THREAD

**Issue by luolongfei** [Ahilmurugesan/socialite-apple-helper#7]
Hello, I found that the condition in line 22 of the Kernel.php file (https://github.com/Ahilmurugesan/socialite-apple-helper/blob/03b1b8f6a1d56ceeeaf9c42b366e7d00b69ea62e/Console/Kernel.php#L22) is always true, which will cause the task to be executed every minute and the client secert will be updated every minute, but I think you want to expire in the client secert It was updated the day before.
Therefore, I think it should be changed to:
```php
return ((config('services.apple.refresh_token_interval_days') * 86400) + config('services.apple.client_secret_updated_at') < time());
```

**Comment by luolongfei** [comment]
Fixed this bug: https://github.com/Ahilmurugesan/socialite-apple-helper/pull/8

**Comment by vonec** [comment]
merged ... that's a good catch :)
